name: grafana

on:
  push:
    branches:
      - 'main'
    paths:
      - grafana/*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          registry: "ghcr.io"
          username: "danopstech"
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: ./grafana
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ghcr.io/danopstech/grafana:latest
